package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
)

// FileSpec defines a template file to be created.
type FileSpec struct {
	RelPath string
	Content string
}

// DefaultFiles returns the standard files generated by cms init.
func DefaultFiles() []FileSpec {
	return []FileSpec{
		{RelPath: "resources/article.yaml", Content: ArticleYAML},
		{RelPath: "migrations/001_create_articles.sql", Content: MigrationSQL},
		{RelPath: ".env.example", Content: DotEnvExample},
		{RelPath: "README.md", Content: QuickStartREADME},
	}
}

// Init creates starter files in the target directory.
func Init(targetDir string, force bool) ([]string, error) {
	if targetDir == "" {
		targetDir = "."
	}

	files := DefaultFiles()

	// 1. Check for existing files if force is false
	if !force {
		for _, f := range files {
			fullPath := filepath.Join(targetDir, f.RelPath)
			if _, err := os.Stat(fullPath); err == nil {
				return nil, fmt.Errorf("file '%s' already exists (use --force to overwrite)", fullPath)
			}
		}
	}

	var createdFiles []string

	// 2. Write files
	for _, f := range files {
		fullPath := filepath.Join(targetDir, f.RelPath)
		dir := filepath.Dir(fullPath)
		if err := os.MkdirAll(dir, 0755); err != nil {
			return nil, fmt.Errorf("failed to create directory '%s': %w", dir, err)
		}

		if err := os.WriteFile(fullPath, []byte(f.Content), 0644); err != nil {
			return nil, fmt.Errorf("failed to write file '%s': %w", fullPath, err)
		}
		createdFiles = append(createdFiles, fullPath)
	}

	return createdFiles, nil
}
